//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICalculator")]
public interface ICalculator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CalculateMethod1", ReplyAction="http://tempuri.org/ICalculator/CalculateMethod1Response")]
    double CalculateMethod1(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CalculateMethod1", ReplyAction="http://tempuri.org/ICalculator/CalculateMethod1Response")]
    System.Threading.Tasks.Task<double> CalculateMethod1Async(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CalculateMethod2", ReplyAction="http://tempuri.org/ICalculator/CalculateMethod2Response")]
    double CalculateMethod2(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CalculateMethod2", ReplyAction="http://tempuri.org/ICalculator/CalculateMethod2Response")]
    System.Threading.Tasks.Task<double> CalculateMethod2Async(double x, double y);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculatorChannel : ICalculator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculatorClient : System.ServiceModel.ClientBase<ICalculator>, ICalculator
{
    
    public CalculatorClient()
    {
    }
    
    public CalculatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double CalculateMethod1(double x, double y)
    {
        return base.Channel.CalculateMethod1(x, y);
    }
    
    public System.Threading.Tasks.Task<double> CalculateMethod1Async(double x, double y)
    {
        return base.Channel.CalculateMethod1Async(x, y);
    }
    
    public double CalculateMethod2(double x, double y)
    {
        return base.Channel.CalculateMethod2(x, y);
    }
    
    public System.Threading.Tasks.Task<double> CalculateMethod2Async(double x, double y)
    {
        return base.Channel.CalculateMethod2Async(x, y);
    }
}
